version: '3'

services:
    twilio-dev:
        build:
            context: .
        ports:
            - '4040:4040' # ngrok web interface
            - '5566:5566' # twilio-run port
            - '5858:5858' # node inspector debug port
            - '5678:5678' # debugpy debug port
        volumes:
            - ./twilio:/usr/src/twilio
            - ./twilio/scratch:/usr/src/twilio/scratch
            - ./ngrok.yml:/root/.ngrok2/ngrok.yml
            - node-modules:/usr/src/twilio/js/sample/node_modules
            - python-bin:/usr/src/twilio/python/sample/bin
            # - global-node-modules:/usr/local/lib/node_modules
            # - local-bin:/usr/local/bin
        env_file: .env

volumes:
    node-modules: # persist local sample node_modules
    python-bin: # persist local sample python bin
    # global-node-modules: # persist global node_modules
    # local-bin: # persist aliases/symlinks
